{{ if not .Values.appKey.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-app-key
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.appKey.key | b64enc | quote }}
{{- end }}
