{{ if not .Values.auspostApi.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-auspost-api-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auspostApi.key | b64enc }}
{{ end }}
