{{ if not .Values.mail.useExistingSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-mail-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mail.username | b64enc | quote }}
  password: {{ .Values.mail.password | b64enc | quote }}
{{ end }}
