{{ if not .Values.cashier.stripe.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-stripe-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  stripe-key: {{ .Values.cashier.stripe.key | b64enc }}
  stripe-secret: {{ .Values.cashier.stripe.secretKey | b64enc }}
  stripe-webhook-secret: {{ .Values.cashier.stripe.webhookSecret | b64enc }}
{{ end }}