{{ if not .Values.oauth.github.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-github-oauth-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth.github.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth.github.clientSecret | b64enc | quote }}
{{ end }}
---
{{ if not .Values.oauth.google.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-google-oauth-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth.google.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth.google.clientSecret | b64enc | quote }}
{{ end }}
---
{{ if not .Values.oauth.facebook.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artichoke3d.fullname" . }}-facebook-oauth-credentials
  labels:
    {{- include "artichoke3d.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth.facebook.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth.facebook.clientSecret | b64enc | quote }}
{{ end }}
